.github/workflows/push-docker-image.yaml, bridge/Dockerfile, bridge/README.md
This pull request resolves #10.
- Introduce Dockerfile to build as Docker image.
- Build Docker image and push it to Docker Hub automatically for each push (merge).
=> build(bridge): introduce dockerfile

bridge/src/confirmation-monitor.ts
It resolves #19. 
After this pull request, it logs message like:
```
[NineChroniclesTransferredEventMonitor] Skipped...
[EthereumBurnEventMonitor] Skipped...
[NineChroniclesTransferredEventMonitor] Skipped...
[EthereumBurnEventMonitor] Skipped...
```
=> feat(bridge): log with its class name as prefix

.github/workflows/build.yaml, bridge/src/index.ts, codecov.yaml
This pull request fixes the bridge logs incorrect transaction hash:
=> fix(bridge): correct mint transaction hash log

bridge-www/src/App.tsx
Before this pull request, it did nothing when the MetaMask's wallet changed.
This pull request makes it update wNCG's amount if the Metamask wallet changed.
1. Prepare multiple metamask accounts having different amount of wNCG.
2. Checkout this pull request and run `yarn start` to use bridge-www app.
- Connect MetaMask to your local bridge-www app if it is not connected yet.
3. Change your MetaMask wallets and see the amount changes.
=> fix(bridge-www): update amount if wallet changed

bridge-www/src/App.tsx, bridge-www/src/components/WrappedNcgBalance.tsx
Before this pull request, the *bridge-www* application hasn't been showing wNCG amount as float. So users did input `100` to exchange 100 wNCG with 1 NCG. It can occur users confused so this pull request fixed it by presenting it as float.
1. Prepare MetaMask account having some wNCG.
2. Checkout this pull request and run `yarn start` to use bridge-www app.
- Connect MetaMask to your local bridge-www app if it is not connected yet.
3. Check your wNCG was represented as decimal.
=> fix(bridge-www): allow 2 places of decimals

bridge/src/ncg-kms-transfer.ts
Before this pull request, `NCGKMSTransfer` included `memo` field though it was `null` into `TransferAsset` plain value.
But on Lib9c side, it hasn't include it if it is `null`. This pull request fixes the bug.
=> fix(bridge): avoid invalid cast for null memo

bridge/.env.example, bridge/src/index.ts
Because the mainnet operation is coming closer, this pull request tried to remove the code to prevent running in mainnet.
But, since #46, the network has been determined by `KMS_PROVIDER_URL` defaultly. So, because the code and .env.example descriptions were staled, this pull request fixes it.
=> docs(bridge): correct .env.example descriptions 

bridge/src/monitors/nine-chronicles-transferred-event-monitor.ts
Originally, I expected authorized block index calculation in `processRemains` function to map 1..50 → 50, 51..100 → 100 but it mapped like 1..49 → 50, 50..99 → 100. It causes bug to make bridge read non-existent block when restarting. This pull request fixes the incorrect calculation.
=> fix(bridge): correct authorized block index calculation

bridge/Dockerfile
This pull request bumps nodejs runtime version into 14.17 from 12. Current docker image doesn't work because nodejs 12 doesn't support `??` operator.
=> feat(bridge): bump node image

bridge/src/observers/nine-chronicles.ts, bridge/test/observers/nine-chronicles.spec.ts
This pull request tries to store intermediate step (i.e. latest tx execution status) and exchange history as record of attempt before `transfer` and `mint`.
It records exchange history before actual execution though the transaction is invalid. But if the transaction is invalid, it expects to record the exchange history with zero amount and empty string (i.e. `""`) as `recipient` if `recipient` is null.
=> fix(bridge): store intermediate step before mint

bridge/src/observers/nine-chronicles.ts
Originally, there was typo.
If someone tried to exchange `1000` and the one already exchanged `50000` NCG and maximum is `10000`,
it printed:
`0xaaaa already exchanged 1000 and users can exchange until 1000 in 24 hours so refund NCG as 1000`.
But it should be:
`0xaaaa already exchanged 50000 and users can exchange until 1000 in 24 hours so refund NCG as 1000`. 
This pull request fixed it.
=> fix(bridge): correct log message

bridge/package.json, bridge/src/index.ts, bridge/src/integrations/index.ts, bridge/src/integrations/pagerduty.ts, bridge/src/observers/burn-event-observer.ts, bridge/src/observers/nine-chronicles.ts, bridge/test/observers/__snapshots__/burn-event-observer.spec.ts.snap, bridge/test/observers/__snapshots__/nine-chronicles.spec.ts.snap, bridge/test/observers/burn-event-observer.spec.ts, bridge/test/observers/nine-chronicles.spec.ts, bridge/yarn.lock
=> feat(bridge): alert error through pagerduty

bridge/src/ncg-kms-transfer.ts
Since NineChronicles network v100080, all actions except for the latest version actions were obsoleted and became not able to be executed. So, this pull request bumps the `transfer_asset` action into `transfer_asset2`.
=> fix(bridge): bump transfer_asset version

bridge/src/observers/nine-chronicles.ts, bridge/test/observers/__snapshots__/nine-chronicles.spec.ts.snap, bridge/test/observers/nine-chronicles.spec.ts
The bridge application has sent Slack messages and PagerDuty alerts when an error is thrown. But when Web3.js threw an object as an error, we could see just `[object Object]`. This pull request makes us see detail values well. You can check it in snapshot files in changes.
If it reverts these changes, then the snapshot test will fail with the below message.
```
-               "value": "{\"code\":-32000,\"message\":\"err: max fee per gas less than block base fee: address 0x9093dd96c4bb6b44A9E0A522e2DE49641F146223, maxFeePerGas: 300000000000 baseFee: 305545815494 (supplied gas 11118348)\"}",
+               "value": "[object Object]",
```
=> fix(bridge): correct error message when object was thrown

scripts/check-dropped-refund-transaction.py
This pull request introduces a script to parse, filter and process dropped refund transactions to CSV.
Currently, there are problems with transaction broadcasting into the 9c main network and there is no way to know all refund transactions until #107. But they should be processed also.
=> feat(scripts): introduce check-dropped-refund-transactions script

bridge-status-bot/app.sh
Manually minted balance should be `54073334`. updated from `44073334`
=> Updated minted balance in the status bot

bridge-status-bot/app.sh
Added Ether Balance threshold and notify message only if the balance is lower than the threshold hold.
* ETH threshold is `3`.
* Tested with a bot message in Slack.
* `Tested with threshold 8 and changed back to 3`
=> add ether balance threshold and notify with @here message

bridge/src/wrapped-ncg-minter.ts, bridge/test/wrapped-ncg-minter.spec.ts
At web3.js 1.5.2, the default transaction type is `0x00`, not `0x02`. The EIP-1559's transaction type is `0x02` and it should be specified explicitly. This pull request does it.
=> fix(bridge): correct EIP-1559 transaction's type

bridge/src/index.ts, bridge/src/wrapped-ncg-minter.ts, bridge/test/wrapped-ncg-minter.spec.ts
#126 deprecated `GAS_TIP_RATIO` but it `EIP-1559` doesn't work well 🤔 So this pull request reverts it for smooth operation.
=> feat(bridge): use `gasPrice` tip again

scripts/observer/__main__.py, scripts/observer/headless.py
I believe this pull request improves observer:
- Use Nine Chronicles headless GraphQL API instead 9cscan.
- Await all handlers. Before this pull request, they didn't work well.
=> fix(scripts): improve observer

bridge/src/interfaces/exchange-history-store.ts, bridge/src/messages/wrapping-retry-ignore-event.ts, bridge/src/observers/nine-chronicles.ts, bridge/src/sqlite3-exchange-history-store.ts, bridge/test/messages/__snapshots__/wrapping-retry-ignore-event.spec.ts.snap, bridge/test/messages/wrapping-retry-ignore-event.spec.ts, bridge/test/observers/nine-chronicles.spec.ts, bridge/test/sqlite3-exchange-history-store.spec.ts
Originally, the bridge application avoids duplicate processing with SQLite's `UNIQUE` constraint. But it treats as an error though it was intended on the side. So this pull request makes it skip that and notify it as a warning to only slack.
=> feat(bridge): skip if the exchange history already exists

bridge/src/observers/burn-event-observer.ts, bridge/src/observers/nine-chronicles.ts, bridge/test/observers/__snapshots__/burn-event-observer.spec.ts.snap, bridge/test/observers/__snapshots__/nine-chronicles.spec.ts.snap
Since #149, the bridge application has started to send processed transactions to OpenSearch. But the number fields like `fee` and `amount`, were treated as `string` types. Because of it, the fields were not able to be `aggregatable` so they can't be aggregated and visualized. This pull request fixed their types to `number` to resolve that situation.
=> fix(bridge): correct opensearch message field type

bridge/.env.example, bridge/src/index.ts, bridge/src/opensearch-client.ts, bridge/test/observers/burn-event-observer.spec.ts, bridge/test/observers/nine-chronicles.spec.ts
This pull request tries to resolve #167.
It started to provide a new environment variable, string-typed, named `OPENSEARCH_INDEX`, and the bridge application became to use the variable as the OpenSearch index name. If it wasn't given, it uses `9c-eth-bridge` as the default value.
Though I don't think it's related to the main feature of the OpenSearch, I requested a review because you're this feature's proposer. If you think this review request is not good, feel free to say about it. Then I'll not request reviews pull requests like this pull request. 🙏🏻
=> feat(bridge): make opensearch index configurable

bridge/package.json, bridge/src/activate-account.ts, bridge/src/index.ts, bridge/src/kms-ncg-signer.ts, bridge/yarn.lock
It makes the bridge application the `aws-kms-*` packages from upstream and deprecated the AWS endpoint feature because it depends on the fork package.
=> fix(bridge): replace @planetarium/aws-kms-provider package with @cloud-cryptographic-wallet/aws-kms-provider

bridge/.env.development, docker-compose.yaml
This pull request makes headless open `5000` number port to use `https://explorer.libplanet.io/localhost`.
=> Setup development environment again with localhost explorer

bridge/src/index.ts, bridge/src/observers/timeout-observer.ts
This pull request resolves #172.
It introduces `TimeoutObserver` and reuses it in nine-chronicles and ethereum both. And it reports error when the observing node didn't notify well while 5 minutes.
=> feat(bridge): report when failed to fetch new block while 5 minutes

bridge/README.md
This pull request resolves #153.
About the *Python 2* part, it was already resolved by https://github.com/planetarium/NineChronicles.EthBridge/commit/e5f86cbef59dbb7e20f0424f6543857b587e3ee9 🙇🏻‍♂️
=> docs(bridge): guide sqlite3 as prerequisite

bridge/.env.example, bridge/src/index.ts, bridge/src/observers/nine-chronicles.ts, bridge/src/policies/exchange-fee-ratio.ts, bridge/test/observers/nine-chronicles.spec.ts, bridge/test/policies/exchange-fee-ratio.spec.ts
This pull request introduces a new environment variable named `ZERO_EXCHANGE_FEE_RATIO_ADDRESSES`. It's a string consisting of addresses joined with `,`. The bridge application will not take exchange fees from the addresses.
=> feat(bridge): introduce `ZERO_EXCHANGE_FEE_RATIO_ADDRESSES` function

bridge/Dockerfile
This pull request bumps the base node image of the bridge Docker image to 16.17.
I bumped it because:
- Node.js 16.17 is current active LTS.
- Node.js 14.17 doesn't support Apple Silicon (darwin-arm64)
=> feat(bridge): upgrade nodejs base image to 16.17

bridge/.env.example, bridge/src/index.ts, bridge/src/messages/index.ts, bridge/src/messages/refund-event.ts, bridge/src/messages/unwrapped-event.ts, bridge/src/messages/unwrapping-failure-event.ts, bridge/src/messages/utils.ts, bridge/src/messages/wrapped-event.ts, bridge/src/messages/wrapping-event.ts, bridge/src/messages/wrapping-failure-event.ts, bridge/src/observers/burn-event-observer.ts, bridge/src/observers/nine-chronicles.ts, bridge/test/messages/__snapshots__/unwrapped-event.spec.ts.snap, bridge/test/messages/__snapshots__/unwrapping-failure-event.spec.ts.snap, bridge/test/messages/__snapshots__/wrapped-event.spec.ts.snap, bridge/test/messages/unwrapped-event.spec.ts, bridge/test/messages/utils.spec.ts, bridge/test/messages/wrapped-event.spec.ts, bridge/test/messages/wrapping-failure-event.spec.ts, bridge/test/observers/__snapshots__/burn-event-observer.spec.ts.snap, bridge/test/observers/__snapshots__/nine-chronicles.spec.ts.snap, bridge/test/observers/burn-event-observer.spec.ts, bridge/test/observers/nine-chronicles.spec.ts
This pull request introduces a new feature to use `9cscan.com` optionally.
Two new environment variables were introduced:
- `USE_NCSCAN_URL`: `boolean`
- `NCSCAN_URL`: `string`
----
=> feat(bridge): use 9cscan optionally

bridge/src/messages/unwrapping-failure-event.ts, bridge/src/messages/utils.ts, bridge/src/messages/wrapping-event.ts, bridge/test/messages/utils.spec.ts
In TypeScript, there is `?` keyword, which makes an argument optional and uses `undefined` when it wasn't provided.
See also https://www.typescriptlang.org/docs/handbook/2/functions.html#optional-parameters.
This pull request resolves #192.
=> refactor(bridge): make argument optional with `?` keyword

bridge/test/aws-dependent/ncg-kms-transfer.aws.spec.ts
Before this pull request, it have to edit minter address, and KMS' address, public key in the code. This pull request just makes tests load them from `.env` file like KMS credentials.
=> test(bridge): make aws-dependent tests' parameters configurable  totally

bridge/src/index.ts, bridge/src/observers/burn-event-observer.ts, bridge/test/observers/burn-event-observer.spec.ts
This pull request tries to prevent Ethereum duplicated transaction processing first.
By recording the histories, it'll prevent duplicated transaction processing because there is `PRIMARY KEY(network, tx_id)` constraint.
=> fix(bridge): record ethereum transaction processing histories

bridge/src/observers/timeout-observer.ts
When using `setTimeout(functionRef, delay, ...)`, the `functionRef`'s `this` seems to become dynamic. To pass the some value, it should give more parameters like `param1`, `param2`. (e.g., `setTimeout(func, 1000, 1, 2, 3)`).
It occurred errors and this pull request corrects it.
=> fix(bridge): correct `setTimeout` usage

bridge/src/headless-graphql-client.ts
There was no timeout while using GraphQL API. This pull request sets it as 10s.
=> fix(bridge): set timeout while using GraphQL API

bridge/src/ncg-kms-transfer.ts
Since #202, the `tx` became a hexadecimal string but the logic to calculate txid wasn't changed. This pull request changes it.
```python
>>> # 's' is raw hexadecimal tx data
>>> m = hashlib.sha256(); m.update(bytes.fromhex(s)); m.digest().hex()
'503b8e53422b652d680f692e4755448971a7709546538c0767129c08edb62e55'
>>> m = hashlib.sha256(); m.update(base64.b64decode(s + "==")); m.digest().hex()
'd89485fc2417fbce04f6f5a9afecd7c6669d2860e666a645019c6d99107d6c57'
```
=> fix(bridge): correct txid calculation

bridge-status-bot/app.sh
Since 2023.02.02., the `:ncg:` emoji was introduced in our internal slack. This pull request makes the `bridge-status-bot` script use it.
=> feat(bridge-status-bot): use ncg emoji

bridge/.env.development
SSIA. Before this pull request, it usually fails to send transaction because its default value is `0.1` so it will use less gas price than the market gas price.
=> feat(bridge): update default `GAS_TIP_RATIO`

bridge/src/ncg-kms-transfer.ts
Since v200030, the `transfer_asset3` became to have the plan to be obsoleted. We should apply this change until 7_200_000 block.
- https://github.com/planetarium/lib9c/blob/79d36a1f6c62dac3398e6c237fda7ef47aa13644/Lib9c/Action/TransferAsset3.cs#L25
- https://github.com/planetarium/lib9c/blob/79d36a1f6c62dac3398e6c237fda7ef47aa13644/Lib9c/ActionObsoleteConfig.cs#L70
=> feat(bridge): use transfer_asset4

scripts/tx_parser_for_minting_cli.py
```
(base) admin@ARYs-MacBook-Pro scripts % python tx_parser_for_minting_cli.py 
9c-scan TX URL:
https://9cscan.com/tx/2c6f6b02f6466f5ba517ebd22e754b49fa2cb83cad9f7c20a8981f291116003a
Loading...
NCG Requested: 41630 / Fee: 1000 / Final: 40630
Sender (9c): 0x6c9d5b2f90ad4dea01ea037a9dfd883b4b875e14
Recipient (ETH): 0x927d1e13d8786d969e13F8fE9e41656842c12C7B
>> npm run mint 0x927d1e13d8786d969e13F8fE9e41656842c12C7B 406.30
```
=> added tx parser for minting cli

bridge/src/ncg-kms-transfer.ts
Since v200080, the transfer_asset4 became to have the plan to be obsoleted. We should apply this change until 7_900_000 block.
=> feat(bridge): use transfer_asset5

bridge/test/observers/nine-chronicles.spec.ts, bridge/test/policies/exchange-fee-ratio.spec.ts
Update maximum NCG Transfer limit Phase #2
Increase Maximum Transfer NCG Amount to 50000 ( before 20000 )
=> feat: update maximum NCG Transfer limit Phase #2

bridge/src/index.ts
Set each providers' weight to make sub_provider's failure not to effect to the whole providers to be failed.
=> feat: update fallback provider weight
