planetarium/NineChronicles.EthBridge

- .github/workflows/build.yaml
> ci(gh-actions): check build automatically

- bridge/src/confirmation-monitor.ts
It should be merged after #20 merged.
It resolves #18.
You can review only f15b9c0 commit.
> fix(bridge): catch and handle error while monitoring

- bridge/src/headless-graphql-client.ts
- bridge/src/index.ts
- bridge/src/interfaces/headless-graphql-client.ts
- bridge/src/interfaces/ncg-transfer.ts
- bridge/src/interfaces/ncg-transferred-event.ts
- bridge/src/ncg-transfer.ts
> feat(bridge): send wNCG to noted address

- bridge/src/index.ts
- bridge/src/wrapped-ncg-token.ts
> fix(bridge): correct wNCG contract address

- bridge/.env.example
- bridge/package-lock.json
- bridge/package.json
- bridge/src/index.ts
This pull request resolves #30
> feat(bridge): send slack notification 

- .github/workflows/build.yaml
- bridge/package-lock.json
- bridge/package.json
- codecov.yaml
This pull request should be merged after #25 merged.
> ci(gh-actions): upload code coverage

- bridge/src/headless-graphql-client.ts
> fix(bridge): correct invalid query argument name

- bridge/src/index.ts
> fix(bridge): send burned ncg correctly

- .github/workflows/build.yaml
- contracts/.solhint.json
- contracts/contracts/Migrations.sol
- contracts/contracts/WrappedNCG.sol
- contracts/package-lock.json
- contracts/package.json
> fix(contracts): setup decimals

- bridge/src/index.ts
- bridge/src/monitors/index.ts
- bridge/src/ncg-transfer.ts
- bridge/src/observers/burn-event-observer.ts
- bridge/src/observers/index.ts
- bridge/src/observers/nine-chronicles.ts
- bridge/test/monitors/nine-chronicles-transferred-event-monitor.spec.ts
- bridge/test/ncg-transfer.spec.ts
- bridge/test/observers/__snapshots__/burn-event-observer.spec.ts.snap
- bridge/test/observers/__snapshots__/nine-chronicles.spec.ts.snap
- bridge/test/observers/burn-event-observer.spec.ts
- bridge/test/observers/nine-chronicles.spec.ts
It continues from #42 and #38.
> fix(bridge): handle decimals

- bridge-www/src/App.tsx
Since #55, the contract was deployed newly but it hadn't been updated. This pull request does it.
> fix(bridge-www): update default contract address

- bridge-www/package.json
- bridge-www/src/App.tsx
- bridge-www/src/components/WrappedNcgBalance.tsx
- bridge-www/yarn.lock
This pull request has similar context with #57. SInce #55, the WNCG's decimal was changed into 18 but it wasn't also applied to bridge-www project. This pull request does it but sadly I couldn't test this changes well so please review these changes.
> fix(bridge-www): fix decimals

- contracts/truffle-config.js
> feat(contracts): add truffle configuration for mainnet

- bridge/package.json
- bridge/src/index.ts
- bridge/src/kms-ncg-signer.ts
- bridge/yarn.lock
This pull request resolves #62. I opened a pull request to resolve at [upstream](https://github.com/odanado/aws-kms-provider) but it was not merged and not released. So I published forked package for it based on https://github.com/moreal/aws-kms-provider/tree/rc-0-3-4 branch.
> fix(bridge): fix invalid signature error

- bridge/src/messages/index.ts
- bridge/src/messages/unwrapping-failure-event.ts
- bridge/src/messages/wrapping-failure-event.ts
- bridge/src/observers/burn-event-observer.ts
- bridge/src/observers/nine-chronicles.ts
- bridge/test/messages/__snapshots__/unwrapping-failure-event.spec.ts.snap
- bridge/test/messages/__snapshots__/wrapping-failure-event.spec.ts.snap
- bridge/test/messages/unwrapping-failure-event.spec.ts
- bridge/test/messages/wrapping-failure-event.spec.ts
- bridge/test/observers/__snapshots__/burn-event-observer.spec.ts.snap
- bridge/test/observers/__snapshots__/nine-chronicles.spec.ts.snap
- bridge/test/observers/burn-event-observer.spec.ts
- bridge/test/observers/nine-chronicles.spec.ts
> fix(bridge): check zero address recipient

- bridge/src/observers/nine-chronicles.ts
> fix(bridge): correct transaction iteration

- bridge/src/observers/nine-chronicles.ts
- bridge/test/observers/nine-chronicles.spec.ts
This pull request resolves #73.
> fix(bridge): check invalid address 

- bridge/src/index.ts
- bridge/src/messages/wrapped-event.ts
- bridge/src/observers/nine-chronicles.ts
- bridge/test/messages/__snapshots__/wrapped-event.spec.ts.snap
- bridge/test/messages/wrapped-event.spec.ts
- bridge/test/observers/__snapshots__/nine-chronicles.spec.ts.snap
- bridge/test/observers/nine-chronicles.spec.ts
This pull request tries to resolve #69.
It starts to collect exchange fee, 1%.
Currently, there is a problem when someone tries to exchange 0.01 NCG with 0.01 fee ratio. Then the NCG fee become 0.0001 NCG and it is invalid in NCG policy (2 decimal places). This seems able to be validated with minimum policy which will be introduced in #74.
> feat(bridge): collect exchange fee

- bridge/src/activate-account.ts
> feat(bridge): introduce activate account script

- bridge/.env.example
- bridge/src/configuration.ts
- bridge/src/index.ts
- bridge/src/interfaces/exchange-history-store.ts
- bridge/src/messages/wrapped-event.ts
- bridge/src/observers/nine-chronicles.ts
- bridge/src/sqlite3-exchange-history-store.ts
- bridge/test/configuration.spec.ts
- bridge/test/messages/__snapshots__/wrapped-event.spec.ts.snap
- bridge/test/messages/wrapped-event.spec.ts
- bridge/test/observers/__snapshots__/nine-chronicles.spec.ts.snap
- bridge/test/observers/nine-chronicles.spec.ts
- bridge/test/sqlite3-exchange-history-store.spec.ts
This pull request tries to resolve #72
> feat(bridge): limit exchange

- bridge/src/observers/nine-chronicles.ts
- bridge/test/observers/nine-chronicles.spec.ts
SSIA. In detail, please see code changes.
> fix(bridge): correct transferredAmountInLast24Hours 

- bridge/src/ncg-kms-transfer.ts
> fix(bridge): correct ncg amount in `NCGKMGTransfer`

- bridge/package.json
- bridge/src/index.ts
- bridge/yarn.lock
> feat(bridge): add timestamp to logs

- bridge/src/index.ts
- bridge/src/wrapped-ncg-minter.ts
- bridge/test/wrapped-ncg-minter.spec.ts
It supports to mint with gas price tip through `GAS_PRICE_TIP_RATIO` environment.
> feat(bridge): mint with gas price tip

- bridge/src/observers/nine-chronicles.ts
> fix(bridge): hard coded blockhash

- bridge/src/activate-account.ts
- bridge/src/headless-graphql-client.ts
- bridge/src/index.ts
- bridge/test/aws-dependent/ncg-kms-transfer.aws.spec.ts
The error with `520` status code occurred often. This pull request tried to bypass it by retrying.
> feat(bridge): retry graphql request

- bridge/src/observers/nine-chronicles.ts
> fix(bridge): correct log

- bridge/src/index.ts
- bridge/src/observers/nine-chronicles.ts
- bridge/src/policies/address-ban.ts
- bridge/test/observers/nine-chronicles.spec.ts
- bridge/test/policies/adress-ban.spec.ts
> feat(bridge): skip transaction sent from banned address 

- bridge/src/observers/burn-event-observer.ts
- bridge/test/observers/burn-event-observer.spec.ts
This pull request resolves #92.
> feat(bridge): send NCG with Ethereum transaction hash as memo

- bridge-status-bot/README.md
- bridge-status-bot/app.sh
I'll turn this script into TypeScript code.
> feat(bridge-status-bot): introduce bridge-status-bot

- bridge/package.json
- bridge/src/wrapped-ncg-minter.ts
- bridge/test/wrapped-ncg-minter.spec.ts
- bridge/tsconfig.json
- bridge/types/web3-core-promievent/index.d.ts
- bridge/yarn.lock
See also https://web3js.readthedocs.io/en/v1.2.11/callbacks-promises-events.html#promievent
> feat(bridge): log transaction hash of mint

- bridge/src/index.ts
- bridge/src/policies/gas-price.ts
- bridge/src/wrapped-ncg-minter.ts
- bridge/test/policies/gas-price.spec.ts
- bridge/test/wrapped-ncg-minter.spec.ts
Since this pull request, the bridge application became to limit gas price to avoid gas price spike.
> feat(bridge): limit gas price

- bridge/src/index.ts
> fix(bridge): ignore uncaught exception

- bridge/src/wrapped-ncg-minter.ts
> fix(bridge): revert transactionHash logging

- bridge/src/observers/burn-event-observer.ts
> fix(bridge): correct log message

- bridge/src/messages/refund-event.ts
- bridge/src/observers/nine-chronicles.ts
- bridge/test/observers/__snapshots__/nine-chronicles.spec.ts.snap
- bridge/test/observers/nine-chronicles.spec.ts
This pull request resolves https://github.com/planetarium/NineChronicles.EthBridge/issues/106.
> feat(bridge): notify refund message

- bridge/src/messages/refund-event.ts
- bridge/test/observers/__snapshots__/nine-chronicles.spec.ts.snap
This pull request fixes incorrect transaction links in refund event.
> fix(bridge): correct refund event transaction link

- .github/workflows/build.yaml
- scripts/observer/requirements-dev.txt
> ci(gh-actions): check types of scripts with mypy

- bridge/.env.example
- bridge/src/headless-graphql-client.ts
- bridge/src/index.ts
- bridge/src/interfaces/headless-graphql-client.ts
- bridge/src/ncg-kms-transfer.ts
- bridge/test/aws-dependent/ncg-kms-transfer.aws.spec.ts
- bridge/test/monitors/nine-chronicles-transferred-event-monitor.spec.ts
- bridge/test/ncg-transfer.spec.ts
- bridge/test/wrapped-ncg-minter.spec.ts
> feat(bridge): stage transactions to multiple headlesses

- scripts/check-dropped-refund-transaction.py
> refactor(scripts): correct typehint

- scripts/observer/__main__.py
- scripts/observer/headless.py
> feat(scripts): remove false alarm

- README.md
- I'm not sure about the `collateral` word. If there is a more natural word, please let me know it, or leave a review 🙏🏻 
- Please check whether the accounts are able to be used as collateral or not. If not, I should remove the account from the table. I took them from the NCG description page.
This resolves #156.
> Describe about collateral

- bridge-www/package.json
- bridge-www/src/App.tsx
- bridge-www/src/components/TextField.tsx
- bridge-www/src/components/WrappedNcgBalance.tsx
- bridge-www/src/index.tsx
- bridge-www/yarn.lock
- Derive the contract address from the wallet's chain id.
- Avoid panic when the amount is invalid
> feat(bridge-www): use nextui react ui library

- bridge/package.json
- bridge/src/activate-account.ts
- bridge/src/index.ts
- bridge/src/kms-ncg-signer.ts
- bridge/yarn.lock
This reverts commit ce395032d3a17672df05a71748545124c7a9cabc.
It makes the bridge application use previous version kms provider package.
> Revert "feat(bridge): use KMS package from upstream"

- scripts/observer/__main__.py
- scripts/observer/parser.py
This pull request resolve #195
> fix(scripts): make observer handle 9cscan

- .github/workflows/build-scripts.yaml
- scripts/observer/requirements-dev.txt
This pull request resolves #198
> build(scripts): add `mypy` as dev dependecy

- bridge/src/messages/unwrapping-retry-ignore-event.ts
- bridge/src/observers/burn-event-observer.ts
- bridge/test/messages/unwrapping-retry-ignore-event.spec.ts
> fix(bridge): skip unwrapping retry events

- scripts/observer/fetch-all-txs.py
- scripts/observer/ncscan.py
- scripts/observer/requirements.txt
> feat(scripts): introduce a new script to fetch all txs

- bridge/Dockerfile
This issue must be researched and recovered.
> fix(bridge): install musl napi dependency manually

- bridge/Dockerfile
> fix(bridge): correct installation path

- bridge-status-bot/app.sh
It must be merged after executing `ERC20.transferOwnership(newOwner)` well.
> feat(bridge-status-bot): update ethereum bridge address to track

- bridge-status-bot/app.sh
This pull request resolves #235
> feat(bridge-status-bot): check safe contract executor's balance too

- docker-compose.yaml
> chore: bump 9c-headless image

- README.md
> docs: describe the cold wallet organization

- README.md
This pull request resolves #241 too.
> docs: describe collateral section with deposit transactions

- bridge/.env.development
> feat(bridge): update default `MAX_GAS_PRICE` value

- bridge/.env.development
- docker-compose.yaml
> chore(bridge): bump headless image

- bridge/.env.development
- bridge/src/index.ts
- bridge/src/observers/nine-chronicles.ts
- bridge/test/observers/__snapshots__/nine-chronicles.spec.ts.snap
- bridge/test/observers/nine-chronicles.spec.ts
Applied Base Fee Policy
set BaseFee 10, for Transfer under 1000 NCG
> feat(bridge): apply base fee policy

- .github/workflows/build-bridge.yaml
- bridge/.dockerignore
- bridge/Dockerfile
- bridge/package.json
- bridge/src/headless-graphql-client.ts
- bridge/src/interfaces/headless-graphql-client.ts
- bridge/src/ncg-kms-transfer.ts
- bridge/test/monitors/nine-chronicles-transferred-event-monitor.spec.ts
- bridge/test/ncg-transfer.spec.ts
- bridge/test/wrapped-ncg-minter.spec.ts
- bridge/yarn.lock
- docker-compose.yaml
- In order to use planetarium tx library, node version > 19.xx is required. => updated to node 20.x
- Updated Dockerfile
- Updated package.json and dependencies
- Added updatedAddress set
Test DONE:
* Bridge Tx: https://planetariumhq.slack.com/archives/C03S6FD3N92/p1689581789441079
* GraphQL updatedAddress:
> used planetarium tx library and modified updatedAddress

- bridge/src/ncg-kms-transfer.ts
updated MEAD gas limit to 4n from 1n
> updated mead gas limit

- README.md
Updated README.md file.
Added mint case for Securing funds for multi-chain partnerships.
> feat: added cold wallet mint case at README

- bridge-status-bot/app.sh
Added check ETH_SAFE_EXECUTOR_BALANCE 
and alert( Mention Here at slack Channel ) if it's balance is less then Threshold( current 1 ETH ).
> feat: updated ETH Balance alert criterion

- bridge/src/index.ts
- bridge/src/observers/nine-chronicles.ts
- bridge/src/policies/exchange-fee-ratio.ts
- bridge/src/spreadsheet-client.ts
- bridge/test/observers/burn-event-observer.spec.ts
- bridge/test/observers/nine-chronicles.spec.ts
- bridge/test/policies/exchange-fee-ratio.spec.ts
Update Fee Policy
Set Fee per Amount Range.
Applied Two Amount Range.
( Keep Base Fee Policy )
```
Bridge fee
<1,000 NCG: 10 NCG fixed
≥1,000 NCG: 1% base fee
>10,000 NCG: 1% base fee for total amount + 2% additional surcharge for the amount exceeding 10,000 NCG
```
---
Local Test Cases
```
case1: 500 NCG Transfer -> 490 NCG ( 10 Base Fee )
case2: 1000 NCG Transfer -> 990 NCG ( 10 Base Fee )
case3: 8000 NCG Transfer -> 7920 NCG ( 1% Fee for Range1 )
case4: 10000 NCG Transfer -> 99000 NCG ( 1% Fee for Range1 )
case5: 12000 NCG Transfer -> 11840 NCG ( Fee 160 = 1% Fee + 2% fee for 2000 )
case6: 20000 NCG Transfer -> 19600 NCG ( Fee 400 = 1% Fee + 2% fee for 10000 )
```
> feat:update fee policy

- bridge/src/whitelist/whitelist-accounts.ts
> feat: added whiteList accounts

- .github/workflows/build-bridge.yaml
> update git build ci workflow

- bridge/src/observers/nine-chronicles.ts
- bridge/src/policies/exchange-fee-ratio.ts
- bridge/src/spreadsheet-client.ts
- bridge/src/whitelist/account-type.ts
- bridge/src/whitelist/whitelist-accounts.ts
- bridge/test/observers/nine-chronicles.spec.ts
- bridge/test/policies/exchange-fee-ratio.spec.ts
- bridge/yarn.lock
* Surcharge based on 24hr transfer
> Surcharge based on 24hr transfer

- bridge/src/observers/nine-chronicles.ts
- bridge/src/policies/exchange-fee-ratio.ts
- bridge/test/observers/__snapshots__/nine-chronicles.spec.ts.snap
- bridge/test/observers/nine-chronicles.spec.ts
- bridge/test/policies/exchange-fee-ratio.spec.ts
> 100% coverage for #291

- bridge/src/whitelist/whitelist-accounts.ts
* allowlisted bsu for 9c ecosystem fund
> minor: allowlisted bsu for 9c ecosystem fund
